mysql:
  host: localhost
  port: 3306
  database: stats
  user: root
  password: password

# If this option is enabled, the Game Points will be synchronized with the PointsAPI.
# Requires PointsAPI installed on the server: https://github.com/teraprath/PointsAPI
use_points_api: false

language:
  prefix: "&8[&cStats&8] "
  player_not_found: "&7Player &4%player% &7not found."
  player_stats_update: "&4%player%'s &7%datatype% has been set to &c%amount%."
  wrong_usage: "&7Wrong usage: &c%usage%"

  # Stats command
  # Placeholder: %player_stats%, %kills%, %deaths%, %wins%, %loses%, %games_played%, %streak%, %game_points%
  stats:
    - "&8&m-------------------"
    - ""
    - "&4%player%'s &7Stats"
    - ""
    - "&7Kills: &c%kills%"
    - "&7Deaths: &c%deaths%"
    - "&7Wins: &c%wins%"
    - "&7Loses: &c%loses%"
    - "&7Games Played: &c%games_played%"
    - "&7Streak: &c%streak%"
    - "&7Game Points: &c%game_points%"
    - "&8&m-------------------"

